# Generated by Django 4.2.7 on 2023-11-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Host', 'Host'), ('User', 'User')], default='User', max_length=50),
        ),
    ]
