# Generated by Django 4.2.7 on 2023-11-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='default/default.jpg', upload_to='profile_pics/'),
        ),
    ]
