# Generated by Django 4.2.7 on 2023-11-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='profile_pics/'),
        ),
    ]
