# Generated by Django 4.2.7 on 2023-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostprofile',
            name='reviews',
            field=models.IntegerField(),
        ),
    ]
