# Generated by Django 4.2.7 on 2023-11-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_hostprofile_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostProfile',
        ),
    ]
