# Generated by Django 4.2.7 on 2023-11-20 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_hostprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('years_hosting', models.PositiveIntegerField()),
            ],
        ),
    ]
