# Generated by Django 4.2.7 on 2023-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default/te.jpg', upload_to='post_pics/'),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
