# Generated by Django 4.2.7 on 2023-11-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_user_post_user_id_post_guests_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default/te.jpg', upload_to='post_pics/'),
        ),
    ]
