# Generated by Django 4.2.7 on 2023-12-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('unusual', 'Unusual'), ('iconic_city', 'Iconic city'), ('mountain', 'Mountain'), ('desert', 'Desert'), ('tropical', 'Tropical'), ('arctic', 'Arctic'), ('forest', 'Forest')], max_length=50, null=True),
        ),
    ]
